
#General settings
[general]
	#When enabled makes seeds drop from grass [Default: false]
	seedsFromGrass = false
	#Makes it so if you hold hot drinks for too long that you begin taking fire damage [Default: false]
	hotBurnsPlayer = false
	#When enabled allows the usage of bonemeal on the mods plants [Default: true]
	bonemealGrow = true
	#When enabled makes seeds drop from grass [Default: false]
	saplingsFromGrass = false
	#Amount of seconds before you start taking fire damage when 'hotBurnsPlayer' is enabled [Default: 15]
	#Range: > 1
	hotTime = 15
	#When enabled the fruity leaves have to be right-clicked to be harvested [Default: false]
	rightClickFruitHarvest = false
	#Enables rakes [Default: true]
	enableRake = true
	#When enabled allows instant-growth using bonemeal on the mods plants [Default: false]
	instantGrow = false
	#The chance in which fruit drop from tree when "rightClickFruitHarvest" isn't enabled (1 in X chance) [Default: 20]
	#Range: > 1
	treeDropChance = 20
	#Enables Crop to Seeds recipes [Default: true]
	crop_to_seeds = true

#Tree settings
[tree]
	#Enable generation of Apple trees [Default: true]
	generateAppleTree = true
	#Enable generation of Lemon trees [Default: true]
	generateLemonTree = true
	#Enable generation of Orange trees [Default: true]
	generateOrangeTree = true
	#Enable generation of Avocado trees [Default: true]
	generateAvocadoTree = true
	#Enable generation of Mango trees [Default: true]
	generateMangoTree = true
	#Enable generation of Pear trees [Default: true]
	generatePearTree = true
	#Enable generation of Olive trees [Default: true]
	generateOliveTree = true
	#Enable generation of Banana trees [Default: true]
	generateBananaTree = true
	#Enable generation of Cherry trees [Default: true]
	generateCherryTree = true

#Crop settings
[crop]
	#Enable generation of wild Nether Flower crops in the nether [Default: true]
	generateNetherFlower = true

